/// Application entrypoint for the RiseTechpreneur mobile app.
///
/// This file wires up global providers, theming, and the root navigation shell.
library;
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:risetechpreneur/presentation/screens/main_navigation.dart';
import 'core/app_theme.dart';
import 'firebase_options.dart'; // Generated by flutterfire configure

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(
    // Riverpod needs a [ProviderScope] at the root of the widget tree.
    const ProviderScope(child: MyApp()),
  );
}

/// Root widget that configures global theme and the initial navigation screen.
class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'RiseTech App',
      debugShowCheckedModeBanner: false,
      // 2. Apply the centralized theme
      theme: AppTheme.lightTheme,
      home: const MainNavigation(),
    );
  }
}
